#!/usr/bin/env bash
#
# bin/fetch-sa3-data
#
# Fetches the ABS Statistical Area Level 3 (SA3) boundaries from the
# Australian Bureau of Statistics ArcGIS REST service, and produces
# db/data/sa3.geojson — the file the Vera Dispatch Manager tutorial
# imports in Module 3 Lesson 4.
#
# This script is run once during chassis preparation. The resulting
# file is vendored in the chassis archive. Tutorial readers don't run
# this script themselves; they receive sa3.geojson as part of the
# chassis. If the ABS publishes updated boundaries (e.g., for a new
# census), re-run this script and re-tag the chassis.
#
# Data provenance:
#   Source:      Australian Bureau of Statistics
#   URL:         https://geo.abs.gov.au/arcgis/rest/services/ASGS2021/SA3/FeatureServer/0
#   Edition:     ASGS Edition 3 (Jul 2021 - Jun 2026)
#   Licence:     Creative Commons Attribution 4.0 International (CC BY 4.0)
#   Datum:       GDA2020 (when fetched from ABS at SRID 4326)
#   Populations: SYNTHETIC — generated by this script. Not real census data.
#                See "Synthetic populations" below.
#
# Requirements:
#   - curl (for HTTP fetch)
#   - jq   (for JSON manipulation)
#
# Usage:
#   bin/fetch-sa3-data
#   # Produces db/data/sa3.geojson

set -euo pipefail

BASE_URL="https://geo.abs.gov.au/arcgis/rest/services/ASGS2021/SA3/MapServer/1/query"       
OUTPUT="db/data/sa3.geojson"
RAW_OUTPUT="db/data/.sa3-raw.geojson"
PAGE_SIZE=2000

# Where to save scratch files
mkdir -p db/data
TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT

# Check dependencies
for cmd in curl jq; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "ERROR: $cmd is not installed. Please install it and retry." >&2
    exit 1
  fi
done

echo "Fetching SA3 boundaries from ABS..."

# The ABS FeatureServer caps responses at 2000 records. Australia has ~358 SA3s,
# so a single page is enough. We still loop in case the limit changes or
# response includes more than expected.

OFFSET=0
PAGE=1
TOTAL_FEATURES=0
> "$TMPDIR/all_features.jsonl"

while :; do
  echo "  Page $PAGE (offset $OFFSET)..."
  PAGE_FILE="$TMPDIR/page_$PAGE.geojson"

  curl -sS --max-time 60 \
    --get \
    --data-urlencode "where=1=1" \
    --data-urlencode "outFields=SA3_CODE_2021,SA3_NAME_2021,SA4_CODE_2021,SA4_NAME_2021,GCCSA_CODE_2021,GCCSA_NAME_2021,STATE_NAME_2021,AREA_ALBERS_SQKM" \
    --data-urlencode "returnGeometry=true" \
    --data-urlencode "outSR=4326" \
    --data-urlencode "f=geojson" \
    --data-urlencode "resultOffset=$OFFSET" \
    --data-urlencode "resultRecordCount=$PAGE_SIZE" \
    "$BASE_URL" \
    -o "$PAGE_FILE"

  if ! jq -e '.features' "$PAGE_FILE" >/dev/null 2>&1; then
    echo "ERROR: Response on page $PAGE is not valid GeoJSON." >&2
    echo "First 500 bytes of response:" >&2
    head -c 500 "$PAGE_FILE" >&2
    exit 1
  fi

  COUNT=$(jq '.features | length' "$PAGE_FILE")
  echo "    received $COUNT features"

  if [ "$COUNT" -eq 0 ]; then
    break
  fi

  jq -c '.features[]' "$PAGE_FILE" >> "$TMPDIR/all_features.jsonl"
  TOTAL_FEATURES=$((TOTAL_FEATURES + COUNT))

  if [ "$COUNT" -lt "$PAGE_SIZE" ]; then
    break
  fi

  OFFSET=$((OFFSET + PAGE_SIZE))
  PAGE=$((PAGE + 1))
done

echo "Fetched $TOTAL_FEATURES features total."

# Build the unmodified raw file (preserved for provenance)
echo "Writing raw file to $RAW_OUTPUT..."
jq -s '{type: "FeatureCollection", features: .}' \
  < "$TMPDIR/all_features.jsonl" \
  > "$RAW_OUTPUT"

# Synthetic populations
#
# ABS does not publish census population on this FeatureServer. Real
# population data requires a separate fetch from census tables (G01).
# For tutorial purposes, we generate synthetic populations within the
# spec's 30,000-130,000 range, weighted by GCCSA — capital city areas
# tend toward higher populations, regional and remote areas toward
# lower.
#
# This is plausibly-shaped data, NOT real census figures. The tutorial
# uses these populations to drive job density weighting in Module 4
# onward; the absolute numbers don't matter, only the relative
# distribution.
#
# Determinism: the population for a given SA3 is a function of its
# SA3_CODE_2021. Re-running the script always produces the same
# populations.

echo "Generating synthetic populations..."

jq '
  # A simple seeded PRNG: hash the SA3 code into a 0-1 number
  def seed_random(code):
    (code | tostring | explode | add) % 100 / 100;

  # Population weight: higher for major-city GCCSAs, lower for remote
  def gccsa_weight(name):
    if name | test("Greater"; "i") then 1.5
    elif name | test("Rest"; "i") then 0.7
    elif name | test("Capital"; "i") then 1.4
    else 1.0
    end;

  .features |= map(
    .properties.population = (
      30000 + (seed_random(.properties.SA3_CODE_2021) * 100000 *
               gccsa_weight(.properties.GCCSA_NAME_2021 // "Other"))
      | floor
    )
  )
' "$RAW_OUTPUT" > "$TMPDIR/with_pop.geojson"

# Lowercase property names and rename to match the lesson's expected schema
echo "Normalising property names..."

jq '
  .features |= map(
    .properties = {
      sa3_code:    .properties.SA3_CODE_2021,
      sa3_name:    .properties.SA3_NAME_2021,
      sa4_name:    .properties.SA4_NAME_2021,
      gccsa_name:  .properties.GCCSA_NAME_2021,
      state:       .properties.STATE_NAME_2021,
      population:  .properties.population
    }
  )
' "$TMPDIR/with_pop.geojson" > "$OUTPUT"

# Final report
FINAL_COUNT=$(jq '.features | length' "$OUTPUT")
SIZE_KB=$(du -k "$OUTPUT" | cut -f1)

echo ""
echo "Done."
echo "  Output: $OUTPUT"
echo "  Features: $FINAL_COUNT"
echo "  Size: ${SIZE_KB} KB"
echo ""
echo "The file is now ready for the import task to consume."
echo "The raw file is preserved at $RAW_OUTPUT for reference."
